In [ ]:
import numpy,math
from sklearn import neighbors as nb
from sklearn import datasets as dt
from sklearn import metrics as mt
from sklearn.model_selection import GridSearchCV

X,Y=dt.load_iris(return_X_y=True)

X_train=X[range(0,150,2),:]
Y_train=Y[range(0,150,2)]

X_test=X[range(1,150,2),:]
Y_test=Y[range(1,150,2)]


In [ ]:
def print_prediction(K,tp):
    clf=nb.KNeighborsClassifier(K,'uniform')
    clf.fit(X_train,Y_train)
    prediction=clf.predict(X_test)
    if tp==False:
        return mt.accuracy_score(Y_test,prediction,normalize=True)
    else:
        print("Predictions\n")
        print(prediction)

        print("\nAccuracy with normalize = ",mt.accuracy_score(Y_test,prediction,normalize=True))
        print(mt.classification_report(Y_test,prediction))
        print(mt.confusion_matrix(Y_test,prediction))

In [ ]:
temp=[]
temp2=[]
for i in range(3,int(math.sqrt(len(X_train)))):
    a=print_prediction(i,False)
    temp.append(a)
    temp2.append(i)
print("K value :- ",end=" ")
print(temp2[temp.index(max(temp))])
print("Accuracy :- ",end=" ")
print(max(temp))

K value :-  5
Accuracy :-  0.9866666666666667


In [ ]:
K_value=max(temp2)
print_prediction(K_value,True)

Predictions

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]

Accuracy with normalize =  0.9866666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       1.00      0.96      0.98        25
           2       0.96      1.00      0.98        25

    accuracy                           0.99        75
   macro avg       0.99      0.99      0.99        75
weighted avg       0.99      0.99      0.99        75

[[25  0  0]
 [ 0 24  1]
 [ 0  0 25]]


In [ ]:
# To Check on which combination we can get the highest accuracy
kn=nb.KNeighborsClassifier()
parameters={'n_neighbors' : [5,10,15,20,25],
            'weights': ['uniform', 'distance'],
            'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']}

grid_kn=GridSearchCV(estimator = kn,
                     param_grid = parameters,
                     scoring = 'accuracy',
                     cv = 5,
                     verbose = 1,
                     n_jobs = -1)

grid_kn.fit(X_train,Y_train)
print(grid_kn.best_estimator_)
print(grid_kn.best_params_)
print(grid_kn.score(X_test,Y_test))

Fitting 5 folds for each of 40 candidates, totalling 200 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  68 tasks      | elapsed:    1.7s
[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed:    1.9s finished


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')
{'algorithm': 'auto', 'n_neighbors': 5, 'weights': 'uniform'}
0.9866666666666667
