In [ ]:
import numpy
from sklearn import datasets as dt
from sklearn import metrics as mt
from sklearn.naive_bayes import GaussianNB as GNB
from sklearn.naive_bayes import BernoulliNB as BNB
from sklearn.naive_bayes import MultinomialNB as MNB

X,Y=dt.load_iris(return_X_y=True)
# print(X)
# print(Y)

X_train=X[range(0,150,2),:]
Y_train=Y[range(0,150,2)]

X_test=X[range(1,150,2),:]
Y_test=Y[range(1,150,2)]


In [ ]:
def print_predict(classify,X_test):
    prediction=classify.predict(X_test)
    print("Predictions\n")
    print(prediction)
    print("\nAccuracy with normalize = ",mt.accuracy_score(Y_test,prediction,normalize=True))
    print(mt.classification_report(Y_test,prediction))
    print(mt.confusion_matrix(Y_test,prediction))

def gaussian(X_train,Y_train,X_test):
    classify=GNB() # for gaussian
    classify.fit(X_train,Y_train)

    print("Attributes\n")
    print(classify.get_params())
    print(classify.class_count_)
    print(classify.class_prior_)
    print(classify.epsilon_)
    print(classify.theta_)
    print(classify.sigma_)

    print_predict(classify,X_test)

def bernoulli(X_train,Y_train,X_test):
    classify=BNB() # for Bernoulli
    classify.fit(X_train,Y_train)

    print("Attributes\n")
    print(classify.get_params())
    print(classify.class_count_)
    print(classify.class_log_prior_)
    print(classify.classes_)
    print(classify.feature_count_)
    print(classify.feature_log_prob_)
    print(classify.n_features_)

    print_predict(classify,X_test)

def multinomial(X_train,Y_train,X_test):
    classify=MNB() # for Multinomial
    classify.fit(X_train,Y_train)

    print("Attributes\n")
    print(classify.get_params())
    print(classify.class_count_)
    print(classify.class_log_prior_)
    print(classify.classes_)
    print(classify.coef_)
    print(classify.feature_count_)
    print(classify.feature_log_prob_)
    print(classify.intercept_)
    print(classify.n_features_)

    print_predict(classify,X_test)

In [ ]:
print("Gaussian\n")
gaussian(X_train,Y_train,X_test)

Gaussian

Attributes

{'priors': None, 'var_smoothing': 1e-09}
[25. 25. 25.]
[0.33333333 0.33333333 0.33333333]
3.1364906666666653e-09
[[5.024 3.48  1.456 0.228]
 [5.992 2.776 4.308 1.352]
 [6.504 2.936 5.564 2.076]]
[[0.146624 0.1016   0.040864 0.006016]
 [0.296736 0.108224 0.220736 0.036096]
 [0.349184 0.079104 0.285504 0.074624]]
Predictions

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 2 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 1 2 2 2 2 2 2 2
 2]

Accuracy with normalize =  0.96
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.92      0.96      0.94        25
           2       0.96      0.92      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75

[[25  0  0]
 [ 0 24  1]
 [ 0  2 23]]


In [ ]:
print("Bernoulli\n")
bernoulli(X_train,Y_train,X_test)

Bernoulli

Attributes

{'alpha': 1.0, 'binarize': 0.0, 'class_prior': None, 'fit_prior': True}
[25. 25. 25.]
[-1.09861229 -1.09861229 -1.09861229]
[0 1 2]
[[25. 25. 25. 25.]
 [25. 25. 25. 25.]
 [25. 25. 25. 25.]]
[[-0.03774033 -0.03774033 -0.03774033 -0.03774033]
 [-0.03774033 -0.03774033 -0.03774033 -0.03774033]
 [-0.03774033 -0.03774033 -0.03774033 -0.03774033]]
4
Predictions

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]

Accuracy with normalize =  0.3333333333333333
              precision    recall  f1-score   support

           0       0.33      1.00      0.50        25
           1       0.00      0.00      0.00        25
           2       0.00      0.00      0.00        25

    accuracy                           0.33        75
   macro avg       0.11      0.33      0.17        75
weighted avg       0.11      0.33      0.17        75

[[25  0  0]
 [25  0  0]
 [25  0  0]]

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print("Multinomial")
multinomial(X_train,Y_train,X_test)

Multinomial
Attributes

{'alpha': 1.0, 'class_prior': None, 'fit_prior': True}
[25. 25. 25.]
[-1.09861229 -1.09861229 -1.09861229]
[0 1 2]
[[-0.71463658 -1.07833227 -1.93399838 -3.65356156]
 [-0.88312064 -1.64488183 -1.2104833  -2.34945771]
 [-0.96868367 -1.75665215 -1.12375164 -2.09770475]]
[[125.6  87.   36.4   5.7]
 [149.8  69.4 107.7  33.8]
 [162.6  73.4 139.1  51.9]]
[[-0.71463658 -1.07833227 -1.93399838 -3.65356156]
 [-0.88312064 -1.64488183 -1.2104833  -2.34945771]
 [-0.96868367 -1.75665215 -1.12375164 -2.09770475]]
[-1.09861229 -1.09861229 -1.09861229]
4
Predictions

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 1 2 1 1 1 2 2 2 2 2 2 2
 2]

Accuracy with normalize =  0.9333333333333333
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.86      0.96      0.91        25
           2       0.95      0.84      0.89        25
